# Spring application configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehr_database  # JDBC URL for PostgreSQL database
    username: ehr_user  # Database username
    password: ehr_password  # Database password
    driver-class-name: org.postgresql.Driver  # PostgreSQL JDBC driver class

# Server configurations
server:
  port: 8080  # Server port

# CORS (Cross-Origin Resource Sharing) configurations
cors:
  allowed-origins: "http://example.com"  # Allowed origins
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"  # Allowed HTTP methods
  allowed-headers: "Content-Type, Authorization"  # Allowed headers
  allow-credentials: true  # Whether credentials such as cookies or HTTP authentication are allowed
  max-age: 3600  # Maximum age (in seconds) for which the preflight response should be cached

# Elation API configurations
elation:
  api:
    baseurl: "https://sandbox.elationemr.com/api/2.0"  # Base URL for Elation API
