# Spring application configurations
spring:
  profiles:
    active: dev  # Default active profile is dev
  application:
    name: ehr-plugin  # Application name
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Database platform
    hibernate:
      ddl-auto: update  # Hibernate DDL auto generation strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL
        format_sql: true  # Format SQL statements for logging

---

spring:
  kafka:
    # Kafka broker address
    bootstrap-servers: localhost:9092

    # Producer properties
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Consumer properties for group1
    consumer:
      group-id: group1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      missing-topics-fatal: false  # Disable fatal error when topic is missing

---

spring:
  kafka:
    # Kafka broker address
    bootstrap-servers: localhost:9092

    # Producer properties
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Consumer properties for group2
    consumer:
      group-id: group2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      missing-topics-fatal: false  # Disable fatal error when topic is missing



# Logging configurations
logging:
  level:
    org.springframework.web: DEBUG  # Logging level for Spring Web packages
