# Spring application configurations
spring:
  liquibase:
    change-log: classpath:/liquibase/master.xml
  profiles:
    active: dev  # Default active profile is dev
  application:
    name: ehr-plugin  # Application name
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Database platform
    hibernate:
      ddl-auto: update  # Hibernate DDL auto generation strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL
        format_sql: true  # Format SQL statements for logging
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# Logging configurations
logging:
  level:
    org.springframework.web: DEBUG  # Logging level for Spring Web packages
