version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ehr_database
      POSTGRES_USER: ehr_user
      POSTGRES_PASSWORD: ehr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
